name: DK-MagicWand-Plugin
version: '${project.version}'
main: org.example.dmytrok.dk_magicwand_plugin.DK_MagicWand_Plugin
commands:
  getSuperWand:
    description: Creating magic wand
    usage: /getMagicWand
    permission: getMagicWand.admin
permissions:
  getSuperWand.admin:
    description: Only admin can get magic wand
    default: op

