name: DK-MagicWand-Plugin
version: '1.0-SNAPSHOT'
main: org.example.dmytrok.dk_magicwand_plugin.DK_MagicWand_Plugin
commands:
  getMagicWand:
    description: Creating magic wand
    usage: /getMagicWand
    permission: getMagicWand.admin
permissions:
  getMagicWand.admin:
    description: Only admin can get magic wand
    default: op

